/**
 * Action types
 */
export const SET_LOADING = 'SET_LOADING';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const GET_PRELOADED_PRODUCTS = 'GET_PRELOADED_PRODUCTS';
export const SET_PRELOADED_PRODUCTS = 'SET_PRELOADED_PRODUCTS';
export const SET_PAGE = 'SET_PAGE';
export const SET_SORT_BY = 'SET_SORT_BY';
export const SET_SHOULD_RENDER_NEXT_PAGE = 'SET_SHOULD_RENDER_NEXT_PAGE';
export const LOAD_MORE_ITEMS = 'LOAD_MORE_ITEMS';
export const SET_FETCHING_NEXT_PAGE = 'SET_FETCHING_NEXT_PAGE';
export const SET_IS_END_OF_PRODUCT_LIST = 'SET_IS_END_OF_PRODUCT_LIST';
